### ISSUE TITLE
Can`t seal with latest version

### ISSUE THREAD

**Issue by dzabel** [bakito/sealed-secrets-web#47]
Hello,

i have tried the latest changes in my environment and now i get this error when i click on "seal" Button:
```
{ "error": "cannot get sealed secret service: services \"sealed-secrets-controller\" is forbidden: User \"system:serviceaccount:sealed-secrets-webui:sealed-secrets-web\" cannot get resource \"services\" in API group \"\" in the namespace \"sealed-secrets\"" } 
```

The WebUI is installed in a different namespace as the controller.
I did not create any RBAC, as i disabled the Button:
```
disableLoadSecrets: false
```

additionally i have set:
```
includeLocalNamespaceOnly = true
image:
  args:
    - --kubeseal-arguments=--controller-namespace=sealed-secrets
```

As i understand the error message now a ClusterRole is needed to access the other namespace. 
I`m not sure what change forces this behaviour. In the past this was not necessary.

**Comment by bakito** [comment]
@dzabel the ClusterRoleBinding is created, when you set the following.

```yaml
includeLocalNamespaceOnly = true
```

**Comment by dzabel** [comment]
Hi,

i already have this setting in place.
Unfortunately a ClusterRole is not what i want.
For creating a ClusterRole cluster-admin privileges is required. 
The previous version didn’t need privileges for reading services in a different namespace. Why this elevated privilege is now needed?

Cheers,

Daniel

**Comment by bakito** [comment]
Sealed-secret-web uses the cli of sealed-secrets to talk with its service to seal and unseal.
To have access to this service it's easiest to instal web along sealed-secrets in the same namespace.

If you install sealed-secrets-web in a different namespace than sealed-secrets itself, then an either a cluster rolebindibg is needed, or an additional role binding in the sealed-secret namespace, that allows the service-account of sealed-secrets-web access to the sealed-secret service.

But this has to be done in the target namespace.
Granting acces accesd to a servis of a different namespace is and should not be part of this chart.

If something changed it might have in sealed-secrets.

You write about `latest changes` what does this mean?

**Comment by bakito** [comment]
Hi Daniel

The older version created only a ClusterRole if RBAC was enabled. 
https://github.com/bakito/sealed-secrets-web/compare/5fc4ec9850bf4b4669f52eec260630df3812c84e...644721b8b9fec88877b85384a30b7a5d6ef4b391
In this chart were some modifications don to only work in the current namespace. Therefore the rbac was applied to either create a Role or ClusterRole

You cli command is talking to the sealed-secrets-controller via a route.
Sealed secrets web is talking directly to the service of the controller and is not making the detour via the route. Hence it needs to access the service of that controller.
And since the secret is located in a different namespace, the service account of sealed secrets web need to have access to that service in the other namespace.

One thing that might hit you could be related with this commit in sealed secrets: https://github.com/bitnami-labs/sealed-secrets/pull/774/files
Which could mean that the service in your sealed secrets installation is not named `sealed-secret-controller` but `sealed-secret`.

You could modify this by setting image args.
`helm upgrade --install sealed-secrets-web bakito/sealed-secrets-web --set image.args={"--kubeseal-arguments=--controller-name=sealed-secrets"}`

Regards,
Marc
